{
 "title": "EventBridge",
 "tags": [
  "Go",
  "EventBridge"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(go_goroutines,service)"
   },
   {
    "name": "http_method",
    "label": "HTTP Method",
    "query": "label_values(server_requests_seconds_bucket_seconds_count{kind=\"http\",operation!=\"\",service=~\"$service\"}, operation)"
   },
   {
    "name": "http_pod",
    "label": "HTTP Pod",
    "query": "label_values(server_requests_seconds_bucket_seconds_count{kind=\"http\",pod!=\"\",service=~\"$service\"}, pod)"
   },
   {
    "name": "http_client_method",
    "label": "HTTP Client Method",
    "query": "label_values(client_requests_seconds_bucket_seconds_count{kind=\"http\",operation!=\"\",service=~\"$service\"}, operation)"
   },
   {
    "name": "grpc_pod",
    "label": "gRPC Pod",
    "query": "label_values(server_requests_seconds_bucket_seconds_count{kind=\"grpc\",pod!=\"\",service=~\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{service=~\"$service\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max FDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_open_fds{service=~\"$service\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_virtual_memory_bytes{service=~\"$service\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{service=~\"$service\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(process_cpu_seconds_total{service=~\"$service\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System MEM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(max(go_memstats_alloc_bytes{service=~\"$service\"}) by (service))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Packet Per Sec",
   "type": "graph",
   "description": "Network Packets Per Second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_network_receive_packets_total{service=\"$service\", device!~\"^(lo|bond).*\"}[5m]) or irate(node_network_receive_packets{service=\"$service\", device!~\"^(lo|bond).*\"}[5m]) ",
     "legendFormat": "Inbound pps"
    },
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_network_transmit_packets_total{service_name=\"$service\", device!~\"^(lo|bond).*\"}[5m]) or irate(node_network_transmit_packets{service_name=\"$service\", device!~\"^(lo|bond).*\"}[5m]) ",
     "legendFormat": "Outbound pps"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "System Network Traffic in bits per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_network_receive_bytes{service=\"$service\", device!~\"^(lo|bond).*\"}[5m]) * 8 or irate(node_network_receive_bytes_total{service=\"$service\", device!~\"^(lo|bond).*\"}[5m]) * 8",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "irate(node_network_transmit_bytes{service=\"$service\", device!~\"^(lo|bond).*\"}[5m]) * 8 or irate(node_network_transmit_bytes_total{service=\"$service\", device!~\"^(lo|bond).*\"}[5m]) * 8",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{service=~\"$service\"}) by (service)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{service}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Objects",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_heap_objects{service=~\"$service\"}) by (service)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{service}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"1\", service=~\"$service\" }",
       "legendFormat": "{{service}} "
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(server_requests_seconds_bucket_seconds_count{kind=\"http\",service=~\"$service\",operation!~\"register|.*ping\"}[2m])) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(server_requests_seconds_bucket_seconds_sum{kind=\"http\",service=~\"$service\",operation!~\"register|.*ping\"}[5m])/ increase(server_requests_seconds_bucket_seconds_count{kind=\"http\",service=~\"$service\",operation!~\"register|.*ping\"}[5m]) >0) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Calls by Pod",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(server_requests_seconds_bucket_seconds_count{kind=\"http\",service=~\"$service\",pod=~\"$http_pod\",operation=~\"$http_method\",operation!~\"register|.*ping\"}[5m])) by (pod,operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pod}} => {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": " HTTP Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(server_requests_code_total{kind=\"http\",code!~\"200\",operation=~\"$http_method\",pod=~\"$http_pod\"}[5m])) BY (job, operation, code) / IGNORING(code) GROUP_LEFT() sum(irate(server_requests_code_total{kind=\"http\",operation=~\"$http_method\",pod=~\"$http_pod\"}[5m])) BY (job, operation) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}  :  {{code}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Error Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(server_requests_code_total{kind=\"http\",service=~\"$service\", code!=\"200\",operation!~\"register|.*ping\"}[5m])) by (operation, code)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}  :  {{code}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP PT99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(server_requests_seconds_bucket_seconds_bucket{kind=\"http\",service=~\"$service\",operation=~\"$http_method\",pod=~\"$http_pod\",operation!~\"register|.*ping\"}[5m])) by (operation,le))",
       "legendFormat": "pt99: {{operation}}"
      }
     ]
    },
    {
     "title": "HTTP PT90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(irate(server_requests_seconds_bucket_seconds_bucket{kind=\"http\",service=~\"$service\",operation=~\"$http_method\",pod=~\"$http_pod\",operation!~\"register|.*ping\"}[5m])) by (operation,le))",
       "legendFormat": "pt90: {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(server_requests_seconds_bucket_seconds_count{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\"}[2m])) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "grpc {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "gRPC Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(server_requests_seconds_bucket_seconds_sum{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\"}[5m])/ increase(server_requests_seconds_bucket_seconds_count{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\"}[5m])>0 ) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "gRPC Calls by Pod",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(server_requests_seconds_bucket_seconds_count{kind=\"grpc\",service=~\"$service\",pod=~\"$grpc_pod\",operation!~\".*Ping\"}[5m])) by (pod,operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "grpc {{pod}} => {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "gRPC Error Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(server_requests_code_total{kind=\"grpc\",service=~\"$service\", code!=\"200\",operation!~\".*Ping\"}[5m])) by (operation, code)",
       "legendFormat": "{{operation}} {{code}}"
      }
     ]
    },
    {
     "title": "gRPC Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(server_requests_code_total{kind=\"grpc\",service=~\"$service\",code!~\"200\",pod=~\"$grpc_pod\",operation!~\".*Ping\"}[5m])) BY ( operation, code) / IGNORING(code) GROUP_LEFT() sum(irate(server_requests_code_total{kind=\"grpc\",service=~\"$service\",pod=~\"$grpc_pod\",operation!~\".*Ping\"}[5m])) BY ( operation) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "grpc {{operation}}  :  {{code}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "gRPC PT99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(server_requests_seconds_bucket_seconds_bucket{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\",pod=~\"$grpc_pod\"}[5m])) by (le, operation))",
       "legendFormat": "grpc: pt99: {{operation}}"
      }
     ]
    },
    {
     "title": "gRPC PT90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(irate(server_requests_seconds_bucket_seconds_bucket{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\",pod=~\"$grpc_pod\"}[5m])) by (le, operation))",
       "legendFormat": "grpc: pt90: {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(server_requests_seconds_bucket_seconds_count{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[2m])) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "event {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(server_requests_seconds_bucket_seconds_sum{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[5m])/ increase(server_requests_seconds_bucket_seconds_count{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[5m])>0 ) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event Calls by Operation",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(server_requests_seconds_bucket_seconds_count{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[5m])) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "event {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event Error Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(server_requests_code_total{kind=\"event\",service=~\"$service\", code!=\"200\",operation!~\".*Ping\"}[5m])) by (operation, code)",
       "legendFormat": "{{operation}} {{code}}"
      }
     ]
    },
    {
     "title": "Event Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(server_requests_code_total{kind=\"event\",service=~\"$service\",code!~\"200\",operation!~\".*Ping\"}[5m])) BY ( operation, code) / IGNORING(code) GROUP_LEFT() sum(irate(server_requests_code_total{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[5m])) BY ( operation) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "event {{operation}}  :  {{code}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event PT99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(server_requests_seconds_bucket_seconds_bucket{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[5m])) by (le, operation))",
       "legendFormat": "event: pt99: {{operation}}"
      }
     ]
    },
    {
     "title": "Event PT90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(irate(server_requests_seconds_bucket_seconds_bucket{kind=\"event\",service=~\"$service\",operation!~\".*Ping\"}[5m])) by (le, operation))",
       "legendFormat": "event: pt90: {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client gRPC QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_requests_seconds_bucket_seconds_count{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\"}[5m])) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client gRPC Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(client_requests_seconds_bucket_seconds_sum{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\"}[5m])/ increase(client_requests_seconds_bucket_seconds_count{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\"}[5m]) > 0 ) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client gRPC Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(client_requests_code_total_total{kind=\"grpc\",service=~\"$service\",operation!~\".*Ping\",code!=\"200\"}[5m])) by (operation,code)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}: {{code}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client HTTP QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_requests_seconds_bucket_seconds_count{kind=\"http\",service=~\"$service\",operation!~\".*/discovery/.*\"}[5m])) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client HTTP Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(client_requests_seconds_bucket_seconds_sum{kind=\"http\",service=~\"$service\",operation!~\".*/discovery/.*\"}[5m])/ increase(client_requests_seconds_bucket_seconds_count{kind=\"http\",service=~\"$service\",operation!~\".*/discovery/.*\"}[5m]) > 0 ) by (operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Client HTTP Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(client_requests_code_total_total{kind=\"http\",service=~\"$service\",operation!~\".*/discovery/.*\",code!=\"200\"}[5m])) by (operation,code)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{operation}}: {{code}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DB QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(db_client_requests_duration_seconds_count{service=~\"$service\"}[5m])) by (name,addr,command)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{addr}} => {{command}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DB Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(db_client_requests_duration_seconds_sum{service=~\"$service\"}[5m])/ increase(db_client_requests_duration_seconds_count{service=~\"$service\"}[5m]) > 0 ) by (name,addr,command)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{addr}} => {{command}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DB Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(db_client_requests_duration_seconds_count{service=~\"$service\",res!=\"ok\"}[5m])) by (name,addr,command,res)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{addr}} => {{command}} => {{res}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_client_requests_duration_seconds_count{service=~\"$service\"}[5m])) by (name,addrs)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{addrs}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(cache_client_requests_duration_seconds_sum{service=~\"$service\"}[5m])/ increase(cache_client_requests_duration_seconds_count{service=~\"$service\"}[5m]) > 0 ) by (name,addrs)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{addrs}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cache_client_requests_duration_seconds_count{service=~\"$service\",res!=\"ok\"}[5m])) by (name,addrs,res)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{addrs}} => {{res}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis Cache Hits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cache_redis_hits_total{service=~\"$service\"}[5m])) by (name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis Cache Misses",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cache_redis_misses_total{service=~\"$service\"}[5m])) by (name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Redis Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cache_redis_hits_total{service=~\"$service\"}[5m])) BY ( name ) / (sum(irate(cache_redis_misses_total{service=~\"$service\"}[5m])) BY ( name ) + sum(irate(cache_redis_hits_total{service=~\"$service\"}[5m])) BY ( name )) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Fanout QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(sync_pipeline_fanout_process_count{service=~\"$service\"}[5m])) by (name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Fanout Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(sync_pipeline_fanout_chan_len{service=~\"$service\"}) by (name)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(job_event_running_workers{service=~\"$service\"}) by (bus_name,topic_type)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{bus_name}} => {{topic_type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Post Event QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(job_event_post_count_total{service=~\"$service\"}[5m])) by (bus_name,event_type)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{bus_name}} => {{event_type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Post Event Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(job_event_post_duration_seconds_sum{service=~\"$service\"}[5m]) / increase(job_event_post_duration_seconds_count{service=~\"$service\"}[5m]) > 0 ) by (bus_name,event_type)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{bus_name}} => {{event_type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Post Event Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(job_event_post_count_total{service=~\"$service\",result!=\"ok\"}[5m])) by (bus_name,event_type)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{bus_name}} => {{event_type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Rule Execute QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(job_rule_execute_total{service=~\"$service\"}[5m])) by (name,event,operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{event}} => {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Rule Execute Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(increase(job_rule_execute_duration_seconds_sum{service=~\"$service\"}[5m]) / increase(job_rule_execute_duration_seconds_count{service=~\"$service\"}[5m]) > 0 ) by (name,event,operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{event}} => {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Rule Execute Error Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(job_rule_execute_total{service=~\"$service\",result!=\"ok\"}[5m])) by (name,event,operation)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}} => {{event}} => {{operation}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}