{{- if .Values.ebJob.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eventbridge.fullname" . }}-job
  labels:
    {{- include "eventbridge.jobLabels" . | nindent 4 }}
    {{- with .Values.ebJob.serviceMonitor.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ebJob.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "eventbridge.jobSelectorLabels" . | nindent 6 }}
  endpoints:
    {{- toYaml .Values.ebJob.serviceMonitor.metricsEndpoints | nindent 4 }}
      {{- with .Values.ebJob.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ebJob.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
