{{ if not .Values.ebJob.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventbridge.fullname" . }}-job
  labels:
    {{- include "eventbridge.jobLabels" . | nindent 4 }}
data:
  secret.yaml: {{ index .Values.ebJob.secret "secret.yaml" | b64enc }}
{{- end }}