{{- if .Values.ebJob.service.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventbridge.fullname" . }}-job
  labels:
    {{- include "eventbridge.jobLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ebJob.service.type }}
  {{- with .Values.ebJob.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    {{- range .Values.ebJob.service.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "eventbridge.jobSelectorLabels" . | nindent 4 }}
{{- end }}