{{- if .Values.ebService.gRPCIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eventbridge.fullname" . }}
  labels:
    {{- include "eventbridge.serviceLabels" . | nindent 4 }}
  {{- with .Values.ebService.gRPCIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ebService.gRPCIngress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ebService.gRPCIngress.tls }}
  tls:
    {{- range .Values.ebService.gRPCIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ebService.gRPCIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "eventbridge.fullname" $ }}-service
                port:
                  name: grpc
          {{- end }}
    {{- end }}
{{- end }}
