{{ if .Values.ebService.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eventbridge.fullname" . }}-service
  labels:
    {{- include "eventbridge.serviceLabels" . | nindent 4 }}
data:
  {{- toYaml .Values.ebService.configmap | nindent 2 }}
{{- end }}