{{ if not .Values.ebService.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventbridge.fullname" . }}-service
  labels:
    {{- include "eventbridge.serviceLabels" . | nindent 4 }}
data:
  secret.yaml: {{ index .Values.ebService.secret "secret.yaml" | b64enc }}
{{- end }}