{{- if .Values.ebService.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eventbridge.serviceServiceAccountName" . }}
  labels:
    {{- include "eventbridge.serviceLabels" . | nindent 4 }}
  {{- with .Values.ebService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ebService.serviceAccount.automount }}
{{- end }}
