{{- if .Values.ebService.service.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventbridge.fullname" . }}-service
  labels:
    monitors.monitoring.coreos.com: 1
    {{- include "eventbridge.serviceLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ebService.service.type }}
  {{- with .Values.ebService.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    {{- range .Values.ebService.service.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "eventbridge.serviceSelectorLabels" . | nindent 4 }}
{{- end }}