{{- if .Values.rocketmq.controller.podDisruptionBudget.enabled -}}
apiVersion: {{ include "eventbridge.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: rmq-controller-pdb
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.rocketmq.controller.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.rocketmq.controller.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.rocketmq.controller.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.rocketmq.controller.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if (semverCompare ">= 1.27-0" .Capabilities.KubeVersion.Version) }}
  {{- with .Values.rocketmq.controller.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  {{- end }}

  selector:
    matchLabels:
      app.kubernetes.io/name: rocketmq
      component: controller
{{- end -}}