on:
  push:
    branches:
      - main

name: Sync to Gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Github to Gitee
        uses: Yikun/hub-mirror-action@v1.5
        with:
          src: github/tianping526
          dst: gitee/tianping5
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          timeout: 600
          debug: true
          force_update: true
          static_list: "helm-charts"
